// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8D9yL3ESTliJ9ZcJ9pJvqGTgLUXta-LU',
    appId: '1:791934098017:web:1e3405d53576fb8b9f2820',
    messagingSenderId: '791934098017',
    projectId: 'cepamm-55a99',
    authDomain: 'cepamm-55a99.firebaseapp.com',
    storageBucket: 'cepamm-55a99.firebasestorage.app',
    measurementId: 'G-G9R1374LL6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQvrpNgZkJl2k2yKCvBTd5y1Q24di8VzM',
    appId: '1:791934098017:ios:8ab528d2a7b6beba9f2820',
    messagingSenderId: '791934098017',
    projectId: 'cepamm-55a99',
    storageBucket: 'cepamm-55a99.firebasestorage.app',
    iosBundleId: 'com.example.residenciaCepamm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8D9yL3ESTliJ9ZcJ9pJvqGTgLUXta-LU',
    appId: '1:791934098017:web:e1af5d97d0700a3f9f2820',
    messagingSenderId: '791934098017',
    projectId: 'cepamm-55a99',
    authDomain: 'cepamm-55a99.firebaseapp.com',
    storageBucket: 'cepamm-55a99.firebasestorage.app',
    measurementId: 'G-VJ3DN50DVP',
  );
}
